### ISSUE TITLE
Class Ch02JtaTest raises org.apache.openejb.OpenEjbContainer$NoModulesFoundException: No modules found to deploy

### ISSUE THREAD

**Issue by nicolasduminil** [PacktPublishing/Jakarta-EE-Cookbook#7]
Hi,
Have tried to use open-ejb as a solution for testing EJBs in a standalone manner but it doesn't seem to work. For example, trying to run mvn test in the ./Jakarta-EE-Cookbook/ch02/ch02-jta raises the following exception:

    INFO - ********************************************************************************
    INFO - OpenEJB http://tomee.apache.org/
    INFO - Startup: Fri Nov 04 13:55:40 CET 2022
    INFO - Copyright 1999-2015 (C) Apache OpenEJB/TomEE Project, All Rights Reserved.
    INFO - Version: 4.7.4
    INFO - Build date: 20160304
    INFO - Build time: 09:05
    INFO - ********************************************************************************
    INFO - openejb.home = /home/nicolas/Jakarta-EE-Cookbook/chapter02/ch02-jta
    INFO - openejb.base = /home/nicolas/Jakarta-EE-Cookbook/chapter02/ch02-jta
    INFO - Created new singletonService org.apache.openejb.cdi.ThreadSingletonServiceImpl@3d51f06e
    INFO - Succeeded in installing singleton service
    INFO - Using 'javax.ejb.embeddable.EJBContainer=true'
    INFO - Cannot find the configuration file [conf/openejb.xml].  Will attempt to create one for the beans deployed.
    INFO - Configuring Service(id=Default Security Service, type=SecurityService, provider-id=Default Security Service)
    INFO - Configuring Service(id=Default Transaction Manager, type=TransactionManager, provider-id=Default Transaction Manager)
    INFO - Configuring Service(id=userDb, type=Resource, provider-id=Default JDBC Database)
    INFO - Creating TransactionManager(id=Default Transaction Manager)
    INFO - Creating SecurityService(id=Default Security Service)
    INFO - Creating Resource(id=userDb)
    INFO - Closing DataSource: userDb
    Tests run: 2, Failures: 0, Errors: 2, Skipped: 0, Time elapsed: 0.933 sec <<< FAILURE!
    validTransaction(com.eldermoraes.ch02.jta1.Ch02JtaTest)  Time elapsed: 0.878 sec  <<< ERROR!
    org.apache.openejb.OpenEjbContainer$NoModulesFoundException: No modules found to deploy.
    1)Maybe descriptors are placed in incorrect location.
    Descriptors could go under: 
    <base-dir>/META-INF or <base-dir>/WEB-INF
    but not directly under <base-dir>
    Check 'Application Discovery via the Classpath' docs page for more info
    2)Maybe no modules are present in the classpath.
    Is 'openejb.base' system property pointing to the intended location?
        at org.apache.openejb.util.Exceptions.newNoModulesFoundException(Exceptions.java:99)
        at org.apache.openejb.OpenEjbContainer$Provider.load(OpenEjbContainer.java:540)
        at org.apache.openejb.OpenEjbContainer$Provider.createEJBContainer(OpenEjbContainer.java:322)
        at javax.ejb.embeddable.EJBContainer.createEJBContainer(EJBContainer.java:127)
        at com.eldermoraes.ch02.jta1.Ch02JtaTest.setUp(Ch02JtaTest.java:39)

I think that you might have lacked some configuration details. In a general manner, there is absolutely no notion of deploying artifacts on application servers, which is quite surprising for a book on Jakarata EE. Where and how the presented code is supposed to be deployed and ran ? Quite disappointing ...

**Comment by eldermoraes** [comment]
Hi there,

All the source code of the book works fine. It was tested over and over again during the time the book was produced, and re-tested by the technical reviewers. So you need to double-check your environment in order to ensure that everything is well prepared.

If you have any questions on how to deploy and run Jakarta EE applications, you can check Chapter 7.
